services:
  postgres:
    image: postgres:15
    container_name: directus_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  directus:
    image: directus/directus:latest
    container_name: directus_app
    restart: unless-stopped
    ports:
      - 8055:8055
    depends_on:
      - postgres
    env_file:
      - .env     # ✅ This line tells Docker to load all your .env variables
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_S3_DRIVER: ${STORAGE_S3_DRIVER}
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
    volumes:
      - ./directus/snapshots:/directus/snapshots  # ✅ Add this line
volumes:
  pgdata:
